/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Jair Ferraz
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
//        executar();
    }
    
    public void executar(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMICadastroLivros = new javax.swing.JMenuItem();
        jMIAlterarLivros = new javax.swing.JMenuItem();
        jMIListarLivros = new javax.swing.JMenuItem();
        jMIExcluirLivros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMICadastroClientes = new javax.swing.JMenuItem();
        jMIAlteraClientes = new javax.swing.JMenuItem();
        jMIAListarClientes = new javax.swing.JMenuItem();
        jMIExcluirClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaDeTrabalho.setPreferredSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout AreaDeTrabalhoLayout = new javax.swing.GroupLayout(AreaDeTrabalho);
        AreaDeTrabalho.setLayout(AreaDeTrabalhoLayout);
        AreaDeTrabalhoLayout.setHorizontalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        AreaDeTrabalhoLayout.setVerticalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        mArquivo.setMnemonic('A');
        mArquivo.setText("Arquivo");

        jMenu1.setMnemonic('L');
        jMenu1.setText("Livros");

        jMICadastroLivros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadastroLivros.setMnemonic('C');
        jMICadastroLivros.setText("Cadastrar");
        jMICadastroLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroLivrosActionPerformed(evt);
            }
        });
        jMICadastroLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMICadastroLivrosKeyPressed(evt);
            }
        });
        jMenu1.add(jMICadastroLivros);

        jMIAlterarLivros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIAlterarLivros.setMnemonic('A');
        jMIAlterarLivros.setText("Alterar");
        jMIAlterarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarLivrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAlterarLivros);

        jMIListarLivros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIListarLivros.setMnemonic('L');
        jMIListarLivros.setText("Listar");
        jMIListarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListarLivrosActionPerformed(evt);
            }
        });
        jMenu1.add(jMIListarLivros);

        jMIExcluirLivros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIExcluirLivros.setMnemonic('E');
        jMIExcluirLivros.setText("Excluir");
        jMenu1.add(jMIExcluirLivros);

        mArquivo.add(jMenu1);

        jMenu3.setMnemonic('C');
        jMenu3.setText("Clientes");

        jMICadastroClientes.setMnemonic('C');
        jMICadastroClientes.setText("Cadastro");
        jMICadastroClientes.setToolTipText("");
        jMICadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMICadastroClientes);

        jMIAlteraClientes.setMnemonic('A');
        jMIAlteraClientes.setText("Alterar");
        jMIAlteraClientes.setMaximumSize(new java.awt.Dimension(80000, 60000));
        jMIAlteraClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlteraClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIAlteraClientes);

        jMIAListarClientes.setMnemonic('L');
        jMIAListarClientes.setText("Listar");
        jMIAListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAListarClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIAListarClientes);

        jMIExcluirClientes.setMnemonic('E');
        jMIExcluirClientes.setText("Excluir");
        jMIExcluirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExcluirClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIExcluirClientes);

        mArquivo.add(jMenu3);

        jMenu4.setMnemonic('R');
        jMenu4.setText("Retiradas");
        mArquivo.add(jMenu4);

        jMenu5.setMnemonic('D');
        jMenu5.setText("Devoluções");
        mArquivo.add(jMenu5);

        jMenuBar1.add(mArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMICadastroLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroLivrosActionPerformed
       abrirCadastrarLivro();
    }//GEN-LAST:event_jMICadastroLivrosActionPerformed

    private void jMICadastroLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMICadastroLivrosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICadastroLivrosKeyPressed

    private void jMIListarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListarLivrosActionPerformed
        
    }//GEN-LAST:event_jMIListarLivrosActionPerformed

    private void jMIAlterarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarLivrosActionPerformed
        alterarCadastroLivro();
    }//GEN-LAST:event_jMIAlterarLivrosActionPerformed

    private void jMIExcluirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExcluirClientesActionPerformed
        abrirExcluirCliente();
    }//GEN-LAST:event_jMIExcluirClientesActionPerformed

    private void jMICadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroClientesActionPerformed
        abrirCadastrarCliente();
    }//GEN-LAST:event_jMICadastroClientesActionPerformed

    private void jMIAlteraClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlteraClientesActionPerformed
        alterarCadastroCliente();
    }//GEN-LAST:event_jMIAlteraClientesActionPerformed

    private void jMIAListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAListarClientesActionPerformed
        abrirListarCliente();
    }//GEN-LAST:event_jMIAListarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaDeTrabalho;
    private javax.swing.JMenuItem jMIAListarClientes;
    private javax.swing.JMenuItem jMIAlteraClientes;
    private javax.swing.JMenuItem jMIAlterarLivros;
    private javax.swing.JMenuItem jMICadastroClientes;
    private javax.swing.JMenuItem jMICadastroLivros;
    private javax.swing.JMenuItem jMIExcluirClientes;
    private javax.swing.JMenuItem jMIExcluirLivros;
    private javax.swing.JMenuItem jMIListarLivros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mArquivo;
    // End of variables declaration//GEN-END:variables

    private void abrirCadastrarLivro() {
        int tipo=1;
        CadastroLivro cl= new CadastroLivro(tipo);
        AreaDeTrabalho.add(cl);
        cl.setVisible(true);
        cl.setTitle(".: Cadastrar :.");
    }

    private void alterarCadastroLivro() {
        int tipo=2;
        CadastroLivro cl= new CadastroLivro(tipo);
        AreaDeTrabalho.add(cl);
        cl.setVisible(true);
        cl.setTitle(".: Editar :.");
    }
    
    private void abrirCadastrarCliente() {
        int tipo=1;
        CadastroCliente cl= new CadastroCliente(tipo);
        AreaDeTrabalho.add(cl);
        cl.setVisible(true);
        cl.setTitle(".: Cadastrar :.");
    }
    
    private void alterarCadastroCliente() {
        int tipo=2;
        CadastroCliente cl= new CadastroCliente(tipo);
        AreaDeTrabalho.add(cl);
        cl.setVisible(true);
        cl.setTitle(".: Editar :.");
    }
    
    private void abrirListarCliente() {
        int tipo=3;
        CadastroCliente cl= new CadastroCliente(tipo);
        AreaDeTrabalho.add(cl);
        cl.setVisible(true);
        cl.setTitle(".: Lista :.");
    }

    private void abrirExcluirCliente() {
        int tipo=4;
        CadastroCliente cl= new CadastroCliente(tipo);
        AreaDeTrabalho.add(cl);
        cl.setVisible(true);
        cl.setTitle(".: Excluir :.");
    }
}
